### ISSUE TITLE
문제는 50이상이었나? 50보다 크면이었나?

### ISSUE THREAD

**Issue by urstory** [esther1104/enjoy_python#1]
https://github.com/esther1104/enjoy_python/blob/1d053d03f964fcf7b2eb0a36ff1d7efc4a5d9100/day12/12-if.py#L17

문제가 50이상이었음? 50보다 크면이었음?

50이상이었으면  x >= 50 이라고 해야하고 50보다 크면 이라고 했으면 x > 50 이라고 했어야 함.

**Comment by bethest4r** [comment]
50보다 크다고 되어 있었음

**Comment by urstory** [comment]
:+1:
